name: Update EasyList

on:
  schedule:
    - cron: "0 0 * * *"   # 每天 0 点 UTC 运行
  workflow_dispatch:       # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run filter script
        run: python filter.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add easylist.txt
          git commit -m "Update easylist" || echo "No changes"
          git push
